services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: development
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    depends_on:
      - development

volumes:
  mongodb: