services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: development
    hostname: py-dev-container
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  mongodb-server:
    image: mongodb/mongodb-community-server:latest
    hostname: mongodb-server
    container_name: mongodb-server
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - development

volumes:
  mongodb: